### ISSUE TITLE
Representing Landmarks in g2o

### ISSUE THREAD

**Issue by Quest2GM** [CogRob/distributed-mapper#9]
Hi @itzsid,

I am trying to figure out how to optimize the landmarks while running distributed mapper. Upon reviewing your paper, (https://itzsid.github.io/publications/Cieslewski18icra.pdf), there does not seem to be any mention of how the landmark positions and the map were updated through DOpt. It seems that, by Prof. Cyrill's lecture (https://www.youtube.com/watch?v=mZBdPgBtrCM), you can actually add landmarks as separate nodes/edges in your pose graph, but there isn't documentation in g2o detailing that adding landmarks is valid. Moreover, you only seem to consider inter-robot and intra-robot communication edges in distributed-mapper, upon looking at this repository's README.

I'm curious to know how map updates were done in your paper, and if distributed-mapper is the right place to be looking. Is there another package available that handles updating landmarks in Occupancy Grid maps?

Thanks for your response!
Quest2GM

**Comment by itzsid** [comment]
Hi @Quest2GM, If a landmark is represented using 6DOF pose (e.g. 3D object poses), then in the current setup you can represent the landmark in the same way as robot pose using `VERTEX_SE3`. Intra-robot edges can represent robot-landmark constraints as well along with odometry constraints. 

However, if landmark type is different from VERTEX_SE3, then the corresponding G2o file has to be updated and the factor graph needs to have the appropriate constraints. It won't affect the distributed mapping component since the inter-robot constraints are between robot poses and not landmarks.

**Comment by Quest2GM** [comment]
Can you clarify what you mean by "the corresponding G2o file has to be updated and the factor graph needs to have appropriate constraints?". If, for example, our landmark type was `VERTEX_SE2,` then exactly what updates need to be made to the g2o file, and what would a constraint look like?

Also, how did you achieve landmark optimization in your paper? Did you use `VERTEX_SE3` landmarks as you describe above?

**Comment by itzsid** [comment]
I would suggest reading GTSAM tutorial on how to represent 2D landmarks and add corresponding contraints: https://gtsam.org/tutorials/intro.html#magicparlabel-65635

In my case, I represented landmark also as `VERTEX_SE3` for 6DOF object pose. In https://itzsid.github.io/publications/Cieslewski18icra.pdf, we didn't optimize landmarks, it was a pose graph optimization.
